#ifndef AGENT_WORKBENCH_WIDGET_H
#define AGENT_WORKBENCH_WIDGET_H

#include <QHash>
#include <QJsonArray>
#include <QJsonObject>
#include <QList>
#include <QSet>
#include <QStringList>
#include <QWidget>

class AgentRuntimeClient;
#ifdef AEGISY_HAS_MONACO
class MonacoEditorBridge;
class TerminalWebBridge;
class QStackedWidget;
class QWebEnginePage;
class QWebEngineProfile;
class QWebEngineView;
#endif
class QButtonGroup;
class QAction;
class QCheckBox;
class QComboBox;
class QLineEdit;
class QListWidgetItem;
class QPlainTextEdit;
class QLabel;
class QListWidget;
class QPushButton;
class QScrollArea;
class QTabBar;
class QTabWidget;
class QTextEdit;
class QTimer;
class QTreeWidget;
class QTreeWidgetItem;
class QVBoxLayout;

class AgentWorkbenchWidget : public QWidget
{
    Q_OBJECT

public:
    explicit AgentWorkbenchWidget(QWidget *parent = nullptr);
    ~AgentWorkbenchWidget() override;

protected:
    bool eventFilter(QObject *watched, QEvent *event) override;

private:
    void buildUi();
    QWidget *buildProductRail();
    QWidget *buildAgentSurface();
    QWidget *buildWorkCanvas();
    QWidget *buildGitPage();
    void setMode(const QString &mode);
    void chooseProject();
    void requestProjectList();
    void populateProjectList(const QJsonObject &result);
    void openProjectFromList(QListWidgetItem *item);
    void beginProjectRootManagement();
    void showProjectRootsDialog(const QJsonObject &result);
    void requestSessionList();
    void populateSessionList(const QJsonObject &result);
    void beginSessionDeletion(QListWidgetItem *item);
    void confirmSessionDeletion(const QJsonObject &preview);
    void beginPortableSessionExport(QListWidgetItem *item);
    void confirmPortableSessionExport(const QJsonObject &preview);
    void beginPortableSessionImport();
    void confirmPortableSessionImport(const QJsonObject &preview);
    void beginRetentionPolicy(const QString &scopeKind, const QString &scopeId,
                              const QString &scopeLabel);
    void showRetentionPolicyDialog(const QJsonObject &result);
    void updateRecoveryUi();
    void requestOperationStatus();
    void updateOperationStatusUi(const QJsonObject &status);
    bool currentOperationStatusBlocked() const;
    bool currentSessionRecoveryRequired() const;
    bool currentSessionDeletionPending() const;
    void loadSessionFromList(QListWidgetItem *item);
    void loadOlderSessionHistory();
    void resetSessionHistoryPagination();
    void submitPrompt();
    void cancelActiveTurn();
    void updateTurnAction();
    void startPendingTurnIfReady();
    void ensureSessionAndSubmit(const QString &prompt, const QJsonArray &context);
    void addContextItem(QJsonObject item);
    void addSelectedFileContext();
    void addEditorSelectionContext();
    void addSearchResultContext();
    void addDiagnosticContext();
    void addTextExcerptContext(const QString &kind, const QString &origin,
                               const QString &label, QPlainTextEdit *source);
    void rebuildContextPanel();
    void clearContextItems();
    QJsonArray includedTurnContext() const;
    void addTimelineItem(const QJsonObject &item, bool prepend = false);
    void addNotice(const QString &text, bool error = false);
    void updateContextStrip();
    void populateDirectory(const QJsonObject &listing);
    void removeTreeItemMappings(QTreeWidgetItem *item);
    void requestDirectoryListing(const QString &directory);
    void markDirectoryUnavailable(const QString &directory, const QString &message);
    void updateWorkspaceWatch(const QString &directory);
    void applyFileFilter();
    bool filterTreeItem(QTreeWidgetItem *item, const QString &query);
    void refreshGitStatus();
    void applyGitDecorations();
    QString gitStatusForPath(const QString &path, bool directory) const;
    void refreshGitWorkspace();
    void requestGitDiff();
    void populateGitOverview(const QJsonObject &overview);
    void populateGitLog(const QJsonObject &log);
    void populateGitDiff(const QJsonObject &diff);
    void startWorkspaceSearch(bool nextPage = false);
    void cancelWorkspaceSearch();
    void appendWorkspaceSearchResults(const QJsonObject &result);
    void openWorkspaceSearchResult(QTreeWidgetItem *item);
    void refreshRepositoryIndex();
    void cancelRepositoryIndex();
    void populateRepositoryIndex(const QJsonObject &result);
    void requestRepositoryMap();
    void openRepositorySymbol(QTreeWidgetItem *item);
    void markRepositoryIndexStale();
    void requestLanguageServers();
    void requestLanguageAction(const QString &action);
    void populateLanguageLocations(const QJsonObject &result, const QString &type);
    void populateLanguageDiagnostics(const QJsonObject &result, bool activateView = true);
    void openLanguageResult(QTreeWidgetItem *item);
    void markLanguageResultsStale();
    void openWorkspaceFile(QTreeWidgetItem *item);
    void requestEditorFile(const QString &path, bool restoring = false);
    void activateEditorBuffer(const QString &path);
    void storeActiveEditorState();
    void closeEditorTab(int index);
    int editorTabIndex(const QString &path) const;
    void updateEditorTab(const QString &path);
    void addRecentFile(const QString &path);
    void updateRecentFilePicker();
    void loadEditorViewState();
    void saveEditorViewState();
    QString editorSettingsKey() const;
    void setEditorSplitEnabled(bool enabled);
    void activateEditorGroup(int group, const QString &path);
    void restoreEditorGroups();
    void setEditorSearchVisible(bool visible, bool replace = false);
    void findEditorText(bool backwards = false);
    void replaceEditorSelection();
    void replaceAllEditorText();
    void updateResponsiveEditorChrome();
    QWidget *buildTerminalPage();
    QWidget *buildWorkspaceEditPage();
    void populateWorkspaceEditPreview(const QJsonObject &preview);
    void showWorkspaceEditFile(QTreeWidgetItem *item);
    void loadMoreWorkspaceEditDiff();
    void requestTerminalList();
    void openTerminal(const QString &kind, const QString &name = QString());
    void activateTerminal(const QString &terminalId);
    void applyTerminalSnapshot(const QJsonObject &terminal, bool resetOutput = false);
    void pollActiveTerminal();
    void updateTerminalControls();
    void addTerminalSelectionContext();
#ifdef AEGISY_HAS_MONACO
    void initializeMonacoEditor(QWidget *parent);
    void syncMonacoModel();
    void syncMonacoModel(int group, const QString &path);
    void handleMonacoContent(const QString &path, const QString &content,
                             int cursorPosition, int anchorPosition);
    void handleMonacoView(int group, const QString &path,
                          int cursorPosition, int anchorPosition,
                          int verticalScroll, int horizontalScroll);
    void initializeTerminalWeb(QWidget *parent);
#endif
    void saveOpenFile();
    void reloadOpenFile();
    void resetEditorModel();
    void updateEditorActions();
    void showEditorFallback(const QString &path, const QJsonObject &metadata,
                            const QString &message);
    void updateRuntimeCapabilityUi();

    AgentRuntimeClient *m_runtime = nullptr;
    QButtonGroup *m_modeGroup = nullptr;
    QLabel *m_runtimeStatus = nullptr;
    QLabel *m_runtimeCapabilityStatus = nullptr;
    QPushButton *m_runtimeRestartButton = nullptr;
    QLabel *m_recoveryBanner = nullptr;
    QLabel *m_operationStatusBanner = nullptr;
    QLabel *m_projectLabel = nullptr;
    QString m_workspaceRootId = QStringLiteral("root-1");
    QString m_workspaceRootPath;
    QLabel *m_contextStrip = nullptr;
    QLabel *m_emptyTimeline = nullptr;
    QPushButton *m_sessionHistoryMoreButton = nullptr;
    QPushButton *m_newSessionButton = nullptr;
    QPushButton *m_openProjectButton = nullptr;
    QPushButton *m_retentionSettingsButton = nullptr;
    QPushButton *m_importSessionButton = nullptr;
    QString m_projectRootsRequestId;
    QString m_projectRootMutationRequestId;
    QString m_projectTrustRequestId;
    QJsonObject m_projectTrustReview;
    QString m_projectListRequestId;
    QString m_projectNavigationRequestId;
    QString m_sessionResumeRequestId;
    QString m_sessionForkRequestId;
    QComboBox *m_modelPicker = nullptr;
    QListWidget *m_projectList = nullptr;
    QLineEdit *m_sessionSearchInput = nullptr;
    QListWidget *m_sessionList = nullptr;
    QScrollArea *m_timelineScroll = nullptr;
    QWidget *m_timelineContent = nullptr;
    QVBoxLayout *m_timelineLayout = nullptr;
    QTextEdit *m_composer = nullptr;
    QWidget *m_contextPanel = nullptr;
    QLabel *m_contextSummary = nullptr;
    QListWidget *m_contextList = nullptr;
    QPushButton *m_attachContextButton = nullptr;
    QPushButton *m_sendButton = nullptr;
    QTabWidget *m_workspaceTabs = nullptr;
    QTreeWidget *m_fileTree = nullptr;
    QLineEdit *m_fileFilter = nullptr;
    QLineEdit *m_workspaceSearchInput = nullptr;
    QComboBox *m_workspaceSearchMode = nullptr;
    QCheckBox *m_workspaceSearchCase = nullptr;
    QPushButton *m_workspaceSearchButton = nullptr;
    QPushButton *m_workspaceSearchCancelButton = nullptr;
    QPushButton *m_workspaceSearchMoreButton = nullptr;
    QTreeWidget *m_workspaceSearchResults = nullptr;
    QLabel *m_workspaceSearchStatus = nullptr;
    QComboBox *m_repositoryMapBudget = nullptr;
    QPushButton *m_repositoryRefreshButton = nullptr;
    QPushButton *m_repositoryCancelButton = nullptr;
    QTabWidget *m_repositoryViews = nullptr;
    QTreeWidget *m_repositorySymbols = nullptr;
    QTreeWidget *m_repositoryDependencies = nullptr;
    QTreeWidget *m_languageResults = nullptr;
    QTreeWidget *m_languageDiagnostics = nullptr;
    QPlainTextEdit *m_diagnosticRawPreview = nullptr;
    QPlainTextEdit *m_repositoryMapPreview = nullptr;
    QLabel *m_repositoryStatus = nullptr;
    QLabel *m_languageStatus = nullptr;
    QPushButton *m_languageDefinitionButton = nullptr;
    QPushButton *m_languageReferencesButton = nullptr;
    QPushButton *m_languageDiagnosticsButton = nullptr;
    QPushButton *m_languageStopButton = nullptr;
    QPushButton *m_languageRawButton = nullptr;
    QPlainTextEdit *m_editor = nullptr;
#ifdef AEGISY_HAS_MONACO
    QStackedWidget *m_editorStack = nullptr;
    QWebEngineView *m_monacoView = nullptr;
    QWebEnginePage *m_monacoPage = nullptr;
    QWebEngineProfile *m_monacoProfile = nullptr;
    MonacoEditorBridge *m_monacoBridge = nullptr;
#endif
    QTabBar *m_editorTabs = nullptr;
    QComboBox *m_recentFilePicker = nullptr;
    QWidget *m_editorSearchBar = nullptr;
    QLineEdit *m_editorFind = nullptr;
    QLineEdit *m_editorReplace = nullptr;
    QCheckBox *m_editorCaseSensitive = nullptr;
    QLabel *m_editorSearchStatus = nullptr;
    QLabel *m_editorPath = nullptr;
    QLabel *m_editorMeta = nullptr;
    QPushButton *m_editorSaveButton = nullptr;
    QPushButton *m_editorReloadButton = nullptr;
    QPushButton *m_editorSplitButton = nullptr;
    QPushButton *m_editorContextButton = nullptr;
    QPlainTextEdit *m_terminalExcerptPreview = nullptr;
    QLabel *m_workspaceEditSummary = nullptr;
    QTreeWidget *m_workspaceEditFiles = nullptr;
    QPlainTextEdit *m_workspaceEditDiff = nullptr;
    QPushButton *m_workspaceEditMoreButton = nullptr;
    QComboBox *m_terminalPicker = nullptr;
    QLabel *m_terminalStatus = nullptr;
    QPushButton *m_terminalNewButton = nullptr;
    QPushButton *m_terminalStopButton = nullptr;
    QPushButton *m_terminalRestartButton = nullptr;
    QPushButton *m_terminalRemoveButton = nullptr;
    QPushButton *m_terminalContextButton = nullptr;
    QLabel *m_gitSummary = nullptr;
    QTreeWidget *m_gitHistory = nullptr;
    QComboBox *m_gitDiffScope = nullptr;
    QPushButton *m_gitRefreshButton = nullptr;
    QPlainTextEdit *m_gitDiffPreview = nullptr;
    QLabel *m_fileStatus = nullptr;
    QTimer *m_workspaceWatchTimer = nullptr;
    QTimer *m_gitStatusTimer = nullptr;
    QTimer *m_terminalPollTimer = nullptr;
    QTimer *m_runtimeHealthTimer = nullptr;
    QHash<QString, QLabel *> m_itemLabels;
    QHash<QString, QPushButton *> m_itemArtifactButtons;
    QHash<QString, QString> m_commandArtifactRequests;
    QHash<QString, QTreeWidgetItem *> m_treeItems;
    QHash<QString, QString> m_workspaceListRequests;
    QHash<QString, QString> m_workspaceReadRequests;
    QHash<QString, QString> m_workspaceMetadataRequests;
    QHash<QString, QString> m_workspaceMetadataMessages;
    QHash<QString, QString> m_gitStatuses;
    QSet<QString> m_watchedDirectories;
    QSet<QString> m_archivedSessionIds;
    QSet<QString> m_recoverySessionIds;
    QSet<QString> m_pendingDeletionSessionIds;
    struct EditorBuffer {
        QString content;
        QString revision;
        QString encoding;
        QString newline;
        QString metadata;
        int cursorPosition = 0;
        int anchorPosition = 0;
        int verticalScroll = 0;
        int horizontalScroll = 0;
        bool saveSupported = false;
        bool modified = false;
        bool conflict = false;
        bool fallback = false;
    };
    struct EditorViewState {
        int cursorPosition = 0;
        int anchorPosition = 0;
        int verticalScroll = 0;
        int horizontalScroll = 0;
    };
    QHash<QString, EditorBuffer> m_editorBuffers;
    QHash<QString, EditorViewState> m_restoredEditorViews;
    QStringList m_recentFiles;
    QSet<QString> m_editorRestoreRequests;
    QString m_editorRestoreActivePath;
    QString m_editorRestoreGroupPaths[2];
    QString m_mode = QStringLiteral("chat");
    QString m_projectId;
    QString m_projectRoot;
    QString m_workspaceWatchId;
    QString m_workspaceSearchRequestId;
    QString m_workspaceSearchId;
    QString m_workspaceSearchCursor;
    QString m_repositoryIndexRequestId;
    QString m_repositoryIndexCancelRequestId;
    QString m_repositoryIndexId;
    QString m_repositoryMapRequestId;
    QString m_repositoryIndexSummary;
    QString m_languageServersRequestId;
    QString m_languageRequestId;
    QString m_diagnosticRawRequestId;
    QString m_diagnosticRawReference;
    QString m_workspaceEditRequestId;
    QString m_workspaceEditArtifactRequestId;
    QString m_workspaceEditId;
    QString m_workspaceEditReference;
    QString m_gitOverviewRequestId;
    QString m_gitLogRequestId;
    QString m_gitDiffRequestId;
    QString m_gitDiffRequestedScope;
    QString m_gitDiffRequestedOid;
    QString m_selectedGitOid;
    QString m_pendingSearchPath;
    QString m_openEditorPath;
    QString m_editorRevision;
    QString m_editorEncoding;
    QString m_editorNewline;
    QString m_editorSaveRequestId;
    QString m_directoryStatus;
    QString m_sessionListRequestId;
    QString m_sessionReadRequestId;
    QString m_operationStatusRequestId;
    QString m_operationStatusSessionId;
    QString m_sessionMutationRequestId;
    QString m_sessionDeletionRequestId;
    QString m_portableSessionRequestId;
    QString m_portableSessionOperation;
    QString m_portableSessionId;
    QString m_portableSessionPath;
    QString m_portableCollisionStrategy;
    QString m_portableTargetProjectId;
    QJsonObject m_portableSessionPackage;
    QString m_retentionPolicyRequestId;
    QString m_retentionScopeKind;
    QString m_retentionScopeId;
    QString m_retentionScopeLabel;
    QString m_sessionHistoryId;
    QString m_sessionHistoryCursor;
    QString m_chatSessionId;
    QString m_chatSessionProjectId;
    QString m_workSessionId;
    QString m_activeTerminalId;
    QString m_terminalAttachRequestId;
    QString m_terminalListRequestId;
    QString m_pendingTerminalKind;
    QString m_pendingTerminalName;
    QString m_terminalSelection;
    QString m_pendingPrompt;
    QString m_activeTurnSessionId;
    QString m_activeTurnId;
    QString m_turnCancelRequestId;
    QJsonArray m_pendingContext;
    QList<QJsonObject> m_contextItems;
    QString m_provider = QStringLiteral("aegisy");
    QString m_model = QStringLiteral("Codex Auto");
    bool m_gitStatusPending = false;
    bool m_sessionListRefreshPending = false;
    bool m_sessionHistoryAppending = false;
    bool m_runtimeRecoveryMode = false;
    bool m_operationStatusKnown = true;
    bool m_operationStatusBlocked = false;
    bool m_runtimeDegradationsAvailable = false;
    QHash<QString, QString> m_runtimeDegradationStates;
    quint64 m_startupRebuiltSessionCount = 0;
    quint64 m_quarantinedSessionCount = 0;
    bool m_workspaceSearchAppending = false;
    bool m_workspaceSearchStale = false;
    bool m_repositoryIndexLoaded = false;
    bool m_repositoryIndexStale = false;
    bool m_languageResultsStale = false;
    int m_structureWorkspaceTab = -1;
    int m_editorWorkspaceTab = -1;
    int m_terminalWorkspaceTab = -1;
    int m_workspaceEditTab = -1;
    int m_gitWorkspaceTab = -1;
    int m_languageResultsView = -1;
    int m_languageDiagnosticsView = -1;
    int m_diagnosticRawView = -1;
    int m_pendingSearchLine = 0;
    int m_pendingSearchColumn = 0;
    quint64 m_workspaceSearchSequence = 0;
    quint64 m_repositoryIndexSequence = 0;
    quint64 m_terminalOutputOffset = 0;
    quint64 m_terminalGeneration = 0;
    qint64 m_workspaceEditOffset = 0;
    int m_sessionHistoryScrollValue = 0;
    int m_sessionHistoryScrollMaximum = 0;
    bool m_terminalRunning = false;
    bool m_terminalStopping = false;
    bool m_turnRunning = false;
    bool m_turnCancelling = false;
    bool m_runtimeRestartRequired = false;
    bool m_terminalWebReady = false;
    int m_terminalRenderRestartAttempts = 0;
    bool m_editorSaveSupported = false;
    bool m_editorConflict = false;
    bool m_editorLoading = false;
    bool m_switchingEditorTab = false;
    bool m_editorSplitEnabled = false;
    bool m_editorRestoreSplitEnabled = false;
    int m_activeEditorGroup = 0;
    int m_editorRestoreActiveGroup = 0;
    QString m_editorGroupPaths[2];
#ifdef AEGISY_HAS_MONACO
    bool m_monacoReady = false;
    bool m_monacoContentWithinLimit = true;
    QStackedWidget *m_terminalStack = nullptr;
    QWebEngineView *m_terminalView = nullptr;
    QWebEnginePage *m_terminalPage = nullptr;
    QWebEngineProfile *m_terminalProfile = nullptr;
    TerminalWebBridge *m_terminalBridge = nullptr;
#endif
};

#endif
