# Deterministically generate an Aegisy artifact manifest from already bundled
# files. This script never downloads, executes, or resolves user environment
# variables; callers must pass paths inside BASE_DIR explicitly.

if(NOT DEFINED BASE_DIR OR NOT DEFINED OUTPUT
        OR NOT DEFINED RUNTIME_PATH OR NOT DEFINED ADAPTER_PATH
        OR NOT DEFINED RUNTIME_ID OR NOT DEFINED RUNTIME_VERSION
        OR NOT DEFINED ADAPTER_ID OR NOT DEFINED ADAPTER_VERSION)
    message(FATAL_ERROR "BASE_DIR, OUTPUT, runtime and adapter metadata are required")
endif()
if(NOT IS_DIRECTORY "${BASE_DIR}")
    message(FATAL_ERROR "BASE_DIR must be an existing directory")
endif()
get_filename_component(BASE_REAL "${BASE_DIR}" REALPATH)

function(reject_control_characters value label)
    foreach(code RANGE 1 31)
        string(ASCII ${code} control_character)
        string(FIND "${value}" "${control_character}" control_index)
        if(NOT control_index EQUAL -1)
            message(FATAL_ERROR "${label} must not contain control characters")
        endif()
    endforeach()
    string(ASCII 127 delete_character)
    string(FIND "${value}" "${delete_character}" delete_index)
    if(NOT delete_index EQUAL -1)
        message(FATAL_ERROR "${label} must not contain control characters")
    endif()
endfunction()

function(require_inside_base candidate label allow_base)
    file(RELATIVE_PATH relative_path "${BASE_REAL}" "${candidate}")
    if(relative_path MATCHES "^(\\.\\./|\\.\\.$)" OR relative_path MATCHES "/\\.\\./"
            OR (NOT allow_base AND relative_path STREQUAL ""))
        message(FATAL_ERROR "${label} must be inside BASE_DIR")
    endif()
endfunction()

function(require_bundled_file input_path output_relative)
    if(NOT IS_ABSOLUTE "${input_path}")
        get_filename_component(input_path "${input_path}" ABSOLUTE BASE_DIR "${BASE_DIR}")
    endif()
    if(NOT EXISTS "${input_path}" OR IS_DIRECTORY "${input_path}" OR IS_SYMLINK "${input_path}")
        message(FATAL_ERROR "artifact is missing or not a regular file")
    endif()
    get_filename_component(input_real "${input_path}" REALPATH)
    require_inside_base("${input_real}" "artifact" FALSE)
    file(RELATIVE_PATH relative_path "${BASE_REAL}" "${input_real}")
    reject_control_characters("${relative_path}" "artifact path")
    string(LENGTH "${relative_path}" relative_path_bytes)
    if(relative_path_bytes GREATER 1024)
        message(FATAL_ERROR "artifact path exceeds the manifest verifier limit")
    endif()
    file(SIZE "${input_real}" artifact_bytes)
    if(artifact_bytes GREATER 536870912)
        message(FATAL_ERROR "artifact exceeds the manifest verifier size limit")
    endif()
    set(${output_relative} "${relative_path}" PARENT_SCOPE)
    set(${output_relative}_absolute "${input_real}" PARENT_SCOPE)
endfunction()

function(json_escape input output)
    set(value "${input}")
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

require_bundled_file("${RUNTIME_PATH}" RUNTIME_RELATIVE)
require_bundled_file("${ADAPTER_PATH}" ADAPTER_RELATIVE)
if(RUNTIME_RELATIVE_absolute STREQUAL ADAPTER_RELATIVE_absolute)
    message(FATAL_ERROR "runtime and adapter must be distinct bundled files")
endif()
if(NOT IS_ABSOLUTE "${OUTPUT}")
    get_filename_component(OUTPUT "${OUTPUT}" ABSOLUTE BASE_DIR "${BASE_REAL}")
endif()
if(EXISTS "${OUTPUT}" AND (IS_SYMLINK "${OUTPUT}" OR IS_DIRECTORY "${OUTPUT}"))
    message(FATAL_ERROR "OUTPUT must be a regular file path, not a symlink or directory")
endif()
get_filename_component(output_directory "${OUTPUT}" DIRECTORY)
if(NOT IS_DIRECTORY "${output_directory}")
    message(FATAL_ERROR "OUTPUT parent must already exist")
endif()
get_filename_component(output_directory_real "${output_directory}" REALPATH)
require_inside_base("${output_directory_real}" "OUTPUT parent" TRUE)
get_filename_component(output_name "${OUTPUT}" NAME)
reject_control_characters("${output_name}" "OUTPUT name")
if(output_name STREQUAL "")
    message(FATAL_ERROR "OUTPUT must name a file")
endif()
set(OUTPUT "${output_directory_real}/${output_name}")
if(OUTPUT STREQUAL RUNTIME_RELATIVE_absolute OR OUTPUT STREQUAL ADAPTER_RELATIVE_absolute)
    message(FATAL_ERROR "OUTPUT must not overwrite a bundled artifact")
endif()
file(SHA256 "${RUNTIME_RELATIVE_absolute}" RUNTIME_SHA256)
file(SHA256 "${ADAPTER_RELATIVE_absolute}" ADAPTER_SHA256)

foreach(value IN ITEMS RUNTIME_ID RUNTIME_VERSION ADAPTER_ID ADAPTER_VERSION)
    string(LENGTH "${${value}}" metadata_bytes)
    if("${${value}}" STREQUAL "" OR metadata_bytes GREATER 128
            OR NOT "${${value}}" MATCHES "^[ -~]+$")
        message(FATAL_ERROR "artifact metadata must be printable ASCII within 128 bytes")
    endif()
endforeach()
if(NOT RUNTIME_ID STREQUAL "aegisy-agentd" OR NOT ADAPTER_ID STREQUAL "codex-app-server")
    message(FATAL_ERROR "artifact identities must match the 0.1 verifier contract")
endif()
json_escape("${RUNTIME_ID}" RUNTIME_ID_JSON)
json_escape("${RUNTIME_VERSION}" RUNTIME_VERSION_JSON)
json_escape("${RUNTIME_RELATIVE}" RUNTIME_PATH_JSON)
json_escape("${ADAPTER_ID}" ADAPTER_ID_JSON)
json_escape("${ADAPTER_VERSION}" ADAPTER_VERSION_JSON)
json_escape("${ADAPTER_RELATIVE}" ADAPTER_PATH_JSON)

set(content "{\n")
string(APPEND content "  \"schema_version\": \"aegisy-artifact-manifest/0.1\",\n")
string(APPEND content "  \"runtime\": {\n")
string(APPEND content "    \"id\": \"${RUNTIME_ID_JSON}\",\n")
string(APPEND content "    \"version\": \"${RUNTIME_VERSION_JSON}\",\n")
string(APPEND content "    \"path\": \"${RUNTIME_PATH_JSON}\",\n")
string(APPEND content "    \"sha256\": \"${RUNTIME_SHA256}\"\n")
string(APPEND content "  },\n")
string(APPEND content "  \"adapter\": {\n")
string(APPEND content "    \"id\": \"${ADAPTER_ID_JSON}\",\n")
string(APPEND content "    \"version\": \"${ADAPTER_VERSION_JSON}\",\n")
string(APPEND content "    \"path\": \"${ADAPTER_PATH_JSON}\",\n")
string(APPEND content "    \"sha256\": \"${ADAPTER_SHA256}\"\n")
string(APPEND content "  }\n")
string(APPEND content "}\n")

file(WRITE "${OUTPUT}" "${content}")
